# .travis.yml for travis-ci.org 
#
# Test configuration:
# - cli          : travis lint ./.travis.yml
# - web interface: https://lint.travis-ci.org/glegoux/mdf

language: python

python:
  - '3.5'

script:
  - ./test/test.sh
